services:
  octosync:
    container_name: octo-sync
    image: ghcr.io/m8tec/octo-sync
    pull_policy: always
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${CSV_MOUNT_PATH:-./playlists}:/playlists:ro
    environment:
      DOTNET_ENVIRONMENT: Production
      Subsonic__Url: ${SUBSONIC_URL:-http://host.docker.internal:5274}
      Subsonic__Username: ${SUBSONIC_USERNAME:-admin}
      Subsonic__Password: ${SUBSONIC_PASSWORD:-admin}
      Sources__Csv__BasePath: ${CSV_BASE_PATH:-/playlists}
      Sources__Tidal__ClientId: ${TIDAL_CLIENT_ID}
      Sources__Tidal__ClientSecret: ${TIDAL_CLIENT_SECRET}
      Sources__Tidal__MaxRequestsPerSecond: ${TIDAL_MAX_REQUESTS_PER_SECOND:-1}
      Sources__Deezer__AccessToken: ${DEEZER_ACCESS_TOKEN}
      Sources__Deezer__MaxRequestsPerSecond: ${DEEZER_MAX_REQUESTS_PER_SECOND:-1}
      Sources__ListenBrainz__BaseUrl: ${LISTENBRAINZ_BASE_URL:-https://api.listenbrainz.org/1/}
      Sources__ListenBrainz__UserName: ${LISTENBRAINZ_USERNAME}
      Sources__ListenBrainz__UserToken: ${LISTENBRAINZ_TOKEN}
      Sources__ListenBrainz__UserAgent: ${LISTENBRAINZ_USER_AGENT:-OctoSync/1.0}
      SyncSettings__IntervalMinutes: ${SYNC_INTERVAL_MINUTES:-10}
      SyncSettings__PlaylistsToSync__Deezer__0: ${DEEZER_PLAYLIST_0}
      SyncSettings__PlaylistsToSync__Deezer__1: ${DEEZER_PLAYLIST_1}
      SyncSettings__PlaylistsToSync__Deezer__2: ${DEEZER_PLAYLIST_2}
      SyncSettings__PlaylistsToSync__Deezer__3: ${DEEZER_PLAYLIST_3}
      SyncSettings__PlaylistsToSync__Deezer__4: ${DEEZER_PLAYLIST_4}
      SyncSettings__PlaylistsToSync__Deezer__5: ${DEEZER_PLAYLIST_5}
      SyncSettings__PlaylistsToSync__Deezer__6: ${DEEZER_PLAYLIST_6}
      SyncSettings__PlaylistsToSync__Spotify__0: ${SPOTIFY_PLAYLIST_0}
      SyncSettings__PlaylistsToSync__Spotify__1: ${SPOTIFY_PLAYLIST_1}
      SyncSettings__PlaylistsToSync__Spotify__2: ${SPOTIFY_PLAYLIST_2}
      SyncSettings__PlaylistsToSync__Spotify__3: ${SPOTIFY_PLAYLIST_3}
      SyncSettings__PlaylistsToSync__Spotify__4: ${SPOTIFY_PLAYLIST_4}
      SyncSettings__PlaylistsToSync__Spotify__5: ${SPOTIFY_PLAYLIST_5}
      SyncSettings__PlaylistsToSync__Spotify__6: ${SPOTIFY_PLAYLIST_6}
      SyncSettings__PlaylistsToSync__Tidal__0: ${TIDAL_PLAYLIST_0}
      SyncSettings__PlaylistsToSync__Tidal__1: ${TIDAL_PLAYLIST_1}
      SyncSettings__PlaylistsToSync__Tidal__2: ${TIDAL_PLAYLIST_2}
      SyncSettings__PlaylistsToSync__Tidal__3: ${TIDAL_PLAYLIST_3}
      SyncSettings__PlaylistsToSync__Tidal__4: ${TIDAL_PLAYLIST_4}
      SyncSettings__PlaylistsToSync__Tidal__5: ${TIDAL_PLAYLIST_5}
      SyncSettings__PlaylistsToSync__Tidal__6: ${TIDAL_PLAYLIST_6}
      SyncSettings__PlaylistsToSync__ListenBrainz__0: ${LISTENBRAINZ_PLAYLIST_0:-daily-jams}
      SyncSettings__PlaylistsToSync__ListenBrainz__1: ${LISTENBRAINZ_PLAYLIST_1:-weekly-exploration}
